# -*- coding: utf-8 -*-
"""visualize_protein

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPdL3Ib-tK3jX7Q8m2jobGKadyb-iB9G
"""

import os
import requests  # For downloading PDB files
from pymol import cmd  # PyMOL API

# Function to download a PDB file from the RCSB PDB
def download_pdb(pdb_id, output_dir='pdb_structures'):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    pdb_filename = os.path.join(output_dir, f"{pdb_id}.pdb")

    # Download PDB file from RCSB PDB
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    try:
        response = requests.get(url)
        response.raise_for_status()  # Check for successful response
        with open(pdb_filename, 'wb') as f:
            f.write(response.content)
        print(f"{pdb_id} has been downloaded to {pdb_filename}.")
        return pdb_filename
    except Exception as e:
        print(f"Error downloading {pdb_id}: {e}")
        return None

# Function to visualize a protein structure with different colors for various elements
def visualize_protein_colored(pdb_id):
    # Download the PDB file
    pdb_filename = download_pdb(pdb_id)
    if pdb_filename is None:
        return

    # Load the structure into PyMOL
    cmd.load(pdb_filename)

    # Set visualization style
    cmd.hide('all')  # Hide all elements initially
    cmd.show('cartoon')  # Show structure in cartoon style

    # Color different protein elements in various colors
    cmd.color('cyan', 'ss h')  # Color alpha helices cyan
    cmd.color('magenta', 'ss s')  # Color beta sheets magenta
    cmd.color('yellow', 'ss l')  # Color loops and other structures yellow

    # Color individual chains if they exist
    cmd.color('red', 'chain A')  # Color chain A red
    cmd.color('green', 'chain B')  # Color chain B green (if present)

    # Zoom into the structure
    cmd.zoom()

    # Save the image
    output_image = f"{pdb_id}_colored_visualization.png"
    cmd.png(output_image, width=800, height=600)
    print(f"Image saved as {output_image}")

# Example usage of the function
if __name__ == "__main__":
    # Specify the protein PDB ID to visualize
    pdb_id = "1A6M"  # Example PDB ID
    visualize_protein_colored(pdb_id)